fix: Pydantic V1 style @validator validators are deprecated
gopro/OpenGoPro pull request #641
Opened 2024-11-27 18:29 UTC by martincarapia

Fix #640

2025-01-07 22:15 UTC, tcamise-gpsw commented
Thanks for this. Can you rebase off the latest `main` to fix the CI issues?

2025-01-08 19:07 UTC, tcamise-gpsw requested changes

2025-01-08 19:07 UTC, tcamise-gpsw commented on demos/python/sdk_wireless_camera_control/open_gopro/models/media_list.py
> +    @field_validator("file_system", mode="before", check_fields=True)
This is breaking [unit testing](https://github.com/gopro/OpenGoPro/actions/runs/12676335033/job/35329323765?pr=641) with:

```python
>       return (GroupedMediaItem if "g" in item else MediaItem)(**item)
E       TypeError: open_gopro.models.media_list.MediaItem() argument after ** must be a mapping, not list
```

2025-03-14 17:45 UTC, tcamise-gpsw commented
The tests are still failing. You can check the log but its basically this:

```
FAILED tests/unit/test_models.py::test_media_list - TypeError: open_gopro.models.media_list.MediaItem() argument after ** must be a mapping, not list
```

2025-03-14 19:39 UTC, martincarapia commented
I'll take a look at it next week during business hours. Thanks for the pointer.

2025-03-21 14:08 UTC, martincarapia commented on demos/python/sdk_wireless_camera_control/open_gopro/models/media_list.py
> +    @field_validator("file_system", mode="before", check_fields=True)
Fixed that type error.

2025-03-21 20:09 UTC, tcamise-gpsw commented on demos/python/sdk_wireless_camera_control/docs/authors.rst
> +* Martin Carapia <martin.carapia@outlook.com>
nice!

2025-03-21 20:09 UTC, tcamise-gpsw approved these changes

2025-03-21 20:10 UTC, merged